version: '3.5'

x-base:
  &default-base
  build:
    context: .
    dockerfile: Dockerfile
  image: ssvnode:latest
  command: make BUILD_PATH=/go/bin/ssvnode start-node
  network_mode: host
#  networks:
#    - bloxapp-docker
  restart: always

x-base-dev:
  &default-dev
  << : *default-base
  image: ssvnode-debug:latest
  build:
    context: .
    dockerfile: dev.Dockerfile
  command:  air
  security_opt:
    - "seccomp:unconfined"
  cap_add:
    - SYS_PTRACE
  volumes:
    - ./:/go/src/github.com/bloxapp/ssv

services:
  ssv-node-1:
    <<: *default-base
    container_name: ssv-node-1
    env_file:
      - .env.node.1

  ssv-node-2:
    <<: *default-base
    container_name: ssv-node-2
    env_file:
      - .env.node.2

  ssv-node-3:
    <<: *default-base
    container_name: ssv-node-3
    env_file:
      - .env.node.3

  ssv-node-4:
    <<: *default-base
    container_name: ssv-node-4
    env_file:
      - .env.node.4


  ssv-node-1-dev:
    << : *default-dev
    container_name: ssv-node-1-dev
#    ports:
#      - 40005:40005
    env_file:
      - .env.node.1
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40005

  ssv-node-2-dev:
    << : *default-dev
    container_name: ssv-node-2-dev
#    ports:
#      - 40006:40006
    env_file:
      - .env.node.2
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40006

  ssv-node-3-dev:
    << : *default-dev
    container_name: ssv-node-3-dev
#    ports:
#      - 40007:40007
    env_file:
      - .env.node.3
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40007

  ssv-node-4-dev:
    << : *default-dev
    container_name: ssv-node-4-dev
#    ports:
#      - 40008:40008
    env_file:
      - .env.node.4
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40008

#networks:
#  bloxapp-docker:
#    driver: bridge
#    name: bloxapp-docker